# Mandatory settings

name: Brett Lischalk
paginate: 25
paginate_path: "/posts/page/:num/"
url: "http://brettlischalk.com"
blog_theme: dark # Or use dark

# Optional settings

discus_identifier: blischalkblog
ga_analytics: UA-4121143-2
rss_enabled: true # Change to false if not
about_enabled: true # Change to true if you wish to show an icon in the navigation that redirects to the about page
social:
  dribbble: # Add your Dribbble handle
  facebook: # Add your Facebook handle
  flickr: # Add your Flickr handle
  github: blischalk
  linkedin: "brett-lischalk-3104537"
  twitter: blischalk
  email: brett@brettlischalk.com
  bitcoin: # Add your Bitcoin link or address

# Important settings (change at own risk)

assets:
  compress:
    css: true
    js: true
  features:
    automatic_img_size: false
  sources:
    - _assets/bower
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .bowerrc
  - .travis.yml
  - .package-lock.json
  - .package
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - node_modules/
gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
permalink: posts/:slug
